name: .NET Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  pull-requests: write     # コメント投稿に必須

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Restore dependencies
        run: dotnet restore CITest.sln
      - name: Build
        run: dotnet build CITest.sln --configuration Release --no-restore
      - name: Test
        run: dotnet test CITest.sln --no-build --configuration Release --verbosity normal --collect:"XPlat Code Coverage"
      # カバレッジレポート生成（Markdown ＋ HTML）
      - name: Generate coverage report
        uses: danielpalme/ReportGenerator-GitHub-Action@v5
        with:
          reports: '**/coverage.cobertura.xml'
          targetdir: 'coveragereport'
          reporttypes: 'HtmlInline;MarkdownSummaryGithub'
      # PR へ MarkdownSummary をコメント／CheckRun として添付
      - name: Publish coverage summary
        run: cat coveragereport/SummaryGithub.md >> $env:GITHUB_STEP_SUMMARY
      - name: Sticky Pull Request Comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: coveragereport/SummaryGithub.md
